### ISSUE TITLE
Ajuste_Tela Informar um Problema

### ISSUE THREAD

**Issue by wilnara** [danielporto/mpi-brasil#70]
O texto está cortado.

https://pmo-social.slack.com/files/USFH7RLSW/F013R0NJE1K/screenshot_20200516-114642.png

**Comment by danielporto** [comment]
O tamanho da fonte deve vir do tema e a área visivel assegurada por uma SafeArea.

**Comment by diego-ch** [comment]
já foi corrigido junto com o #93
